name: "build-latest"

on:
  push:
    branches:
      - "build"
    paths:
      - "src/**"
      - ".github/workflows/**"
  pull_request:
    branches:
      - "build"
    paths:
      - "src/Dockerfile*"

jobs:
  docker_buildx_debian:
    runs-on: ubuntu-latest
    timeout-minutes: 100
    steps:
      - uses: actions/checkout@v3
        name: Checkout
  
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
  
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/xterm-inator/docker-nginx-certbot
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Build and push latest Debian image
        uses: docker/build-push-action@v5.1.0
        with:
          context: ./src
          file: ./src/Dockerfile
          platforms: |
            linux/amd64
            linux/386
            linux/arm64
            linux/arm/v7
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
